# Generated by Django 2.2.4 on 2019-08-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190806_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksprofile',
            name='link',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
