# Generated by Django 2.2.4 on 2019-08-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_worksprofile_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracurricularprofile',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='careerprofile',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='careerprofile',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='careerprofile',
            name='designation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='careerprofile',
            name='from_year',
            field=models.CharField(default='2019', max_length=4),
        ),
        migrations.AlterField(
            model_name='careerprofile',
            name='place',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='educationprofile',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='educationprofile',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='educationprofile',
            name='degree',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='educationprofile',
            name='from_year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='educationprofile',
            name='place',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='offerprofile',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='skillprofile',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='worksprofile',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
