# Generated by Django 2.2.4 on 2019-08-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190821_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationprofile',
            name='from_year',
            field=models.CharField(default='2019', max_length=4),
        ),
    ]
