# Generated by Django 2.2.4 on 2019-09-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#557A95', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(default='#557A95', max_length=100),
        ),
    ]
