# Generated by Django 2.2.4 on 2019-11-15 09:12

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190918_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_site',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bannermedia',
            name='media',
            field=models.FileField(upload_to=users.models.banner_media_user_aware_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['3gp', 'png', 'jpg', 'gif', 'jpeg', 'PNG', 'JPEG', 'JPG'])]),
        ),
    ]
