# Generated by Django 2.2.4 on 2019-08-06 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import resumes.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='screenshot',
            field=models.ImageField(null=True, upload_to='templates/screenshots/'),
        ),
        migrations.CreateModel(
            name='TemplateAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.FileField(upload_to=resumes.models.get_asset_upload_to)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
