# Generated by Django 2.2.4 on 2019-08-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_auto_20190806_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='js',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='template',
            name='styles',
            field=models.TextField(default=''),
        ),
    ]
