# Generated by Django 2.2.4 on 2019-08-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_auto_20190806_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='js',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='styles',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
