# Generated by Django 2.2.4 on 2019-08-06 12:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_auto_20190806_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='gjs_components',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
