# Generated by Django 2.2.4 on 2019-09-18 23:55

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0007_contactformdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBDumps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('file', models.FileField(upload_to='db-dumps/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
