# Generated by Django 2.2.4 on 2020-03-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0008_dbdumps'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='fonts',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
