# Generated by Django 2.2.4 on 2020-03-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0009_template_fonts'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='full_content',
            field=models.TextField(blank=True, help_text='This is HTML with fonts, css, js', null=True),
        ),
    ]
