# Generated by Django 2.2.4 on 2020-03-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0010_template_full_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
