# Generated by Django 2.2.4 on 2019-08-05 16:14

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post-header-images'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog-post-headers'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
