# Generated by Django 2.2.4 on 2019-09-13 16:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_title'),
        ('blogs', '0006_auto_20190821_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('screenshot', models.ImageField(null=True, upload_to='templates/screenshots/')),
                ('template_folder', models.CharField(default='', max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteBlogTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Client')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Template')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
